name: Build & test on Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: przemek83/workflows/.github/workflows/build-and-test-cpp.yml@main
    with:
      platform: windows-latest
