name: Build & test on Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: przemek83/workflows/build-and-test-cpp.yml@main
    with:
      platform: ubuntu-latest
